controller, labels:don't take managed-by from CR
kubevirt/cluster-network-addons-operator pull request #1078
Opened 2021-11-11 11:51 UTC by alonSadan

**What this PR does / why we need it**:
When CNAO is deployed by HCO, HCO puts `managed-by` label with HCO value on
networkAddonsConfig. networkAddonsConfig controller then takes this value and inherit it
to the deployed components. This cause a wrong result of a CNAO component labeled
as managed by HCO.

This commit makes that `managed-by` label will not be taken from networkAddonsConfig,
and test it against an example component - ovs.

Signed-off-by: alonsadan <asadan@redhat.com>

Fixes #1051 
**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2021-11-11 12:53 UTC, alonSadan commented
[I made a stupid miske and fixed it](https://github.com/kubevirt/cluster-network-addons-operator/compare/bed8338b6bfcc711d398fe72b4a0f5f39565a407..d581e304991a702e9e64c87538c35061d1e430da)
I wonder if the controller init tests are enough or we need the relatively extensive e2e I added?

2021-11-11 14:20 UTC, alonSadan commented
[another stupid mistake](https://github.com/kubevirt/cluster-network-addons-operator/compare/d581e304991a702e9e64c87538c35061d1e430da..653dfebc46413fe6a38938641dd4eada03b7fba1) hope it will be OK this time.

2021-11-11 17:38 UTC, RamLavi commented on test/e2e/workflow/deployment_test.go
> +	"sigs.k8s.io/controller-runtime/pkg/client"
this one belong somewhere in the second group no? 
```
	framework "github.com/operator-framework/operator-sdk/pkg/test"
	"github.com/pkg/errors"
	v1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/util/retry"
```

2021-11-11 18:48 UTC, RamLavi requested changes
change looks good!
added some comments for the tests section

2021-11-11 18:48 UTC, RamLavi commented on test/e2e/workflow/deployment_test.go
> +					return deamonSetLabels[names.PART_OF_LABEL_KEY] == partOfLabelCRVal && deamonSetLabels[names.VERSION_LABEL_KEY] == versionLabelCRVal &&
when one of these fail, does the failed test show which of them was it? if not, then it would make it hard for a tester to see what actually failed

2021-11-11 18:48 UTC, RamLavi commented on test/e2e/workflow/deployment_test.go
> +			It("Should take the `part-of`, `version` and `component` labels value and apply it to the deployed component daemonset", func() {
in daemonsets and deployment we need to check the spec.labels and the spec.template.spec.labels. this way there is no need to check the actual pod

I would remove the pods check and add the deployemtn one

2021-11-11 18:48 UTC, RamLavi commented on test/e2e/workflow/deployment_test.go
> +			It("Should NOT apply `managed-by` label value to the deployed component pods", func() {
ditto, would change to deployemnt and also check template

2021-11-11 18:48 UTC, RamLavi commented on test/e2e/workflow/deployment_test.go
> +				}, 2*time.Minute, time.Minute).Should(BeTrue(),
I would directly check that it has the correct value, and not check that it doesn't have a specific wrong one, what do you think?

2021-11-24 22:19 UTC, RamLavi commented on test/e2e/workflow/deployment_test.go
> +	"sigs.k8s.io/controller-runtime/pkg/client"
done

2021-11-30 09:18 UTC, RamLavi commented
/retest

2021-12-01 19:12 UTC, RamLavi commented
Closing This PR in favor of https://github.com/kubevirt/cluster-network-addons-operator/pull/1102

2021-12-01 19:12 UTC, closed without merging