language: Replace master with main/control-plain
kubevirt/cluster-network-addons-operator pull request #1103
Opened 2021-12-02 08:58 UTC by qinqon

**What this PR does / why we need it**:
As part of removing offending language this change do the following:
- master branch -> main branch
- master node -> control-plane node

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2021-12-02 09:04 UTC, qinqon commented
PR at CNAO to change it https://github.com/kubevirt/cluster-network-addons-operator/pull/1103

2021-12-02 11:27 UTC, RamLavi requested changes
big Like, Added comments

2021-12-02 11:27 UTC, RamLavi commented on tools/bumper/cnao_repo_commands_test.go
> +			newPr := getFakePrWithTitle("CNAO test-component to 0.0.2", "main")
currently go-git does not support a repo opened with default branch name other than `master` ([see https://github.com/go-git/go-git/issues/363](https://github.com/go-git/go-git/blob/4ec1753b4e9324d455d3b55060020ce324e6ced2/repository.go#L88))

I suggest we do it manually on our own by setting HEAD to main. please change `newLocalGitRepo` as follows:
```
func setBranchAsHead(repo *git.Repository, branchName string) error {
	h := plumbing.NewSymbolicReference(plumbing.HEAD, plumbing.NewBranchReferenceName(branchName))
	if err := repo.Storer.SetReference(h); err != nil {
		return err
	}
	return nil
}

func newLocalGitRepo(repoDir string, tagCommitMap map[string]string) *gitRepo {
	By(fmt.Sprintf("creating new repository on directory: %s", repoDir))
	repo, err := git.PlainInit(repoDir, false)
	Expect(err).ToNot(HaveOccurred(), "Should succeed cloning git repo")

	setBranchAsHead(repo, "main")

	initializeRepo(repo, repoDir, tagCommitMap)

	return &gitRepo{
		repo:     repo,
		localDir: repoDir,
	}
}
```
I think this should solve your issue

2021-12-02 11:32 UTC, qinqon commented on pkg/network/placement_configuration.go
> +				"node-role.kubernetes.io/control-plane": "",
Why, it will create the netaddonsconfig with the new defaults, it's not going to change the old noes right ?

2021-12-02 11:43 UTC, RamLavi approved these changes
/lgtm

2021-12-03 07:15 UTC, qinqon commented
/approve

2021-12-06 12:29 UTC, RamLavi commented
/retest

2021-12-08 06:47 UTC, RamLavi commented
/retest

2021-12-08 08:49 UTC, merged