Add test cases for runbook URLs
kubevirt/cluster-network-addons-operator pull request #1227
Opened 2022-02-17 08:43 UTC by assafad

This PR adds a new module for monitoring tests and adds new tests cases for alert definitions. We expect to see "runbook_url" annotations in alerts and those urls must be accessible.

Signed-off-by: assafad aadmi@redhat.com

```release-note
None
```

2022-02-17 08:44 UTC, assafad commented
/hold

2022-02-17 08:46 UTC, assafad commented
Hi @RamLavi, @sradco, @machadovilaca. can you please review this PR?

2022-02-21 15:15 UTC, RamLavi requested changes
/ok-to-test

2022-02-21 15:15 UTC, RamLavi commented on test/e2e/workflow/monitoring_test.go
> +	monitoringv1 "github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1"
please separate import groups with new line:
1. standard imports like "context"
2. third part imports like "monitoringv1 "github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1"
3. test related imports like "github.com/onsi/ginkgo"

2022-02-21 15:30 UTC, assafad commented on test/e2e/workflow/monitoring_test.go
> +	monitoringv1 "github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1"
Done

2022-02-21 16:36 UTC, assafad commented on test/e2e/workflow/monitoring_test.go
> +	monitoringv1 "github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1"
Thanks, added another one

2022-02-22 08:13 UTC, assafad commented
/unhold
/retest

2022-02-22 13:07 UTC, RamLavi commented
/hold
@assafad I need to revive this [PR](https://github.com/kubevirt/cluster-network-addons-operator/pull/1126), so we add your P on top of it. better to put it in a separate test module.

2022-03-10 12:57 UTC, RamLavi commented
Hey @assafad , FYI the new monitoring lane PR #1250  is now merged, so feel free to move this PR on top of it

2022-03-13 11:17 UTC, assafad commented
/hold

2022-03-15 13:14 UTC, assafad commented
/unhold

2022-03-16 14:15 UTC, RamLavi requested changes

2022-03-16 14:51 UTC, assafad commented on test/e2e/monitoring/rules_test.go
> +		Context("CNAO alerts", func() {
Done

2022-03-17 08:46 UTC, RamLavi commented
/test pull-e2e-cluster-network-addons-operator-monitoring-k8s

2022-03-17 09:24 UTC, RamLavi commented
/lgtm
/approve

2022-03-17 11:55 UTC, RamLavi commented
@assafad the PR is approved. Feel free to remove the hold flag when you are ready to merge

2022-03-17 11:56 UTC, merged