Kubemacpool: Parameterize "runAsNonRoot" in the yaml
kubevirt/cluster-network-addons-operator pull request #1568
Opened 2023-06-18 07:31 UTC by RamLavi

**What this PR does / why we need it**:
In order to make kubemacpool pods work with restricted psa policy it should have runAsNonRoot: true.
However, once the pod's securityContext has runAsNonRoot: true it should also have a specific rusAsUser.
Having a specific user is problematic on Openshift since it may configure a range of valid ids (example of a possible error - spec.containers[0].securityContext.runAsUser: Invalid value: 127: must be in the ranges: [1000670000, 1000679999]).
(issue [here](https://issues.redhat.com/browse/CNV-29823))

According to "What happens if I use runAsUser in my workloads?" section in https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/1417 the suggested solution is -
```
If you are unable to change the image, for Openshift distributions you MUST leave the RunAsUser and RunAsNonRoot fields empty and let the Openshift SCC inject the values when your workload is qualified to the SCC policy.
```
This is the solution chosen.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2023-06-18 08:05 UTC, RamLavi commented
getting `could not apply (apps/v1, Kind=Deployment) cluster-network-addons/kubemacpool-cert-manager: could not create (apps/v1, Kind=Deployment) cluster-network-addons/kubemacpool-cert-manager: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal string into Go struct field PodSecurityContext.spec.template.spec.securityContext.runAsNonRoot of type bool`

also tried to use the more specific parameter types:
```
var nonRootTrue = true
var nonRootUser int64 = 107
data.Data["RunAsNonRoot"] = &nonRootTrue
data.Data["RunAsUser"] = &nonRootUser
```
didn't work as well..

@oshoval did you encounter this issue? I would expect ksd to have the same issue..

2023-06-19 06:14 UTC, oshoval commented
There is no quote here
https://github.com/kubevirt/cluster-network-addons-operator/pull/1499/files#diff-8041a1f861576736acd26091b5c7806c2735246aa93d254b335c5bd8795e8255R79

Maybe try to align the same thing ?
I don't know, because Alona worked on that, please ask her

2023-06-19 07:31 UTC, qinqon requested changes

2023-06-19 07:31 UTC, qinqon commented on pkg/network/kubemacpool.go
> +		data.Data["RunAsUser"] = "null"
this is the same as not set them up ? I would prefer not to set it at all instead of "null"

2023-06-19 08:27 UTC, RamLavi commented
> There is no quote here https://github.com/kubevirt/cluster-network-addons-operator/pull/1499/files#diff-8041a1f861576736acd26091b5c7806c2735246aa93d254b335c5bd8795e8255R79

yep, that was it. But sorry to bother you I thought you worked on it

2023-06-19 08:35 UTC, oshoval commented
> > There is no quote here https://github.com/kubevirt/cluster-network-addons-operator/pull/1499/files#diff-8041a1f861576736acd26091b5c7806c2735246aa93d254b335c5bd8795e8255R79
> 
> yep, that was it. But sorry to bother you I thought you worked on it

all good, gg

2023-06-19 09:11 UTC, oshoval commented
/retest 

podman issues, need to bump job image for those

2023-06-19 19:46 UTC, RamLavi commented
/retest

2023-06-20 07:09 UTC, qinqon approved these changes
/lgtm
/approve

2023-06-20 07:09 UTC, merged