go modules: Allowlist specific hashicorp modules
kubevirt/cluster-network-addons-operator pull request #1595
Opened 2023-08-14 13:20 UTC by oshoval

**What this PR does / why we need it**:
Due to [1] we need to make sure not to use BSL modules.

Luckily the current we use have not changed.
The ones that are not changed are SDK/API and general Go libraries.
 "HashiCorp APIs, SDKs, and almost all other libraries will remain MPL 2.0." [1] [2]

This commit creates a github action which whitelists them.
Any other module of hashicorp will be rejected, 
and will need to be manually examined if it uses MPL (or other non restrictive license) or BSL.

[1] https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license
[2] https://github.com/cncf/foundation/issues/617#issuecomment-1675803976

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

2023-08-14 13:26 UTC, oshoval commented
/cc @maya-r

2023-08-14 20:05 UTC, maya-r commented
I wonder what happened to our fossa lanes, which seem to be deactivated for kubevirt/kubevirt, which served this purpose but more widely. (However, I am not opposed to a list of allowed modules)

2023-08-15 11:04 UTC, oshoval commented
Print all errors at once
Remove IFS because lines dont start / end with whitespace, and even if so, it won't affect

2023-08-23 11:43 UTC, phoracek requested changes

2023-08-23 11:43 UTC, phoracek commented on .github/workflows/check_hashicorp_modules.yaml
> +                    echo "found non whitelisted hashicorp module: $module"
```suggestion
                    echo "found non allowlisted hashicorp module: $module"
```

2023-08-23 11:43 UTC, phoracek commented on .github/workflows/check_hashicorp_modules.yaml
> +        echo "All hashicorp modules are whitelisted"
```suggestion
        echo "All included hashicorp modules are allowlisted"
```

2023-08-23 12:30 UTC, oshoval commented on .github/workflows/check_hashicorp_modules.yaml
> +            echo "non whitelisted hashicorp modules found. exiting with error"
It is in the commit message, self explanatory isn't it ?
Will add if you prefer of course.

```
This commit creates a github action which allowlists them.
Any other module of hashicorp will be rejected, and will need
to be manually examined if it uses MPL (or other non restrictive license)
or BSL.
```

2023-08-23 12:50 UTC, oshoval commented
Thanks 
Addressed comments

2023-08-23 13:17 UTC, phoracek commented on .github/workflows/check_hashicorp_modules.yaml
> +            echo "non whitelisted hashicorp modules found. exiting with error"
When the check fails on my PR, i will not be looking for the PR that added the check. I would like the message on my PR to tell me what I should do to get it merged

2023-08-23 13:54 UTC, merged

2023-08-24 06:29 UTC, oshoval commented
Thanks,
Since we want to use it on all of our repos, should we just copy the file all over?
or 
1. Have the other repos fetch the list from CNAO (the list will resides on a dedicated file)
2. Have CNAO run those checks when it clones the components during e2e, it will detect problems on component bumping, not on component pushes, but maybe it is good enough?

Not sure it worth it, but it will allow central changes, which is nice

2023-08-24 16:28 UTC, phoracek commented
I would vote to just copy it. It would be simpler and it would keep those repos independent

2023-09-07 11:17 UTC, oshoval commented
It seems MPL2 need to be in exception list [1], [2]

but we need to do so only for the direct dependencies (BenTheElder raised it, and also on [1])

still not sure about those, monitoring the decisions of kubevirt maintainers

[1] https://github.com/cncf/foundation/issues/617#issuecomment-1695913854
[2] https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2023-06-27.json