fix ClusterServiceVersion manifest to not use deprecated version
kubevirt/cluster-network-addons-operator pull request #522
Opened 2020-09-02 09:56 UTC by RamLavi

**What this PR does / why we need it**:
Currently manifest templator created the field customresourcedefinitions.owned[0].version
using the deprecated crd version field.
Lets move to updated versions field.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2020-09-02 10:02 UTC, qinqon commented
/lgtm
/approve

2020-09-02 10:02 UTC, phoracek requested changes

2020-09-02 10:02 UTC, phoracek commented on tools/manifest-templator/manifest-templator.go
> +
Whitespace!

2020-09-02 10:04 UTC, RamLavi commented
/hold

2020-09-02 10:05 UTC, RamLavi commented on tools/manifest-templator/manifest-templator.go
> +
fixed

2020-09-02 10:05 UTC, RamLavi commented
/unhold

fixed whitespace

2020-09-02 10:08 UTC, qinqon commented
/lgtm

2020-09-02 10:09 UTC, phoracek reviewed
/lgtm

2020-09-02 10:19 UTC, rhrazdil commented
/lgtm

2020-09-03 06:51 UTC, RamLavi commented
/hold

checking if the error is relevant to this PR: `both or none of the KubeMacPool ranges needs to be configured: invalid configuration`

2020-09-03 07:07 UTC, RamLavi commented
/retest

local testing did  not recreate. checking if consistent of prow

2020-09-03 08:16 UTC, RamLavi commented
will open a flaky bug for the error that occurred, but otherwise moving on with the PR as it seems not relevant to this PR.

2020-09-03 08:17 UTC, RamLavi commented
/hold cancel

2020-09-03 08:19 UTC, merged