specialCleanUp, fix reset cause by []error{nil}
kubevirt/cluster-network-addons-operator pull request #596
Opened 2020-10-08 13:23 UTC by RamLavi

**What this PR does / why we need it**:
Currently, if cleanUpMultusOldName returns nil,
it gets appended to the errList, and since
len([]error{nil}) != 0, it tried to access
Error() method of nil.
Let's fix this by making sure we are not
appending nil to the list, and also by adding a
protection in errorListToMultiLineString

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2020-10-08 14:09 UTC, rhrazdil requested changes
There is an outdated comment

2020-10-08 14:34 UTC, RamLavi commented on pkg/network/multus.go
>  	// if we found the object
right, Done

2020-10-08 16:36 UTC, rhrazdil commented
/lgtm

2020-10-09 09:25 UTC, qinqon commented
/lgtm
/approve

2020-10-09 09:27 UTC, merged