bumper, Change bumper fail policy
kubevirt/cluster-network-addons-operator pull request #708
Opened 2020-12-20 14:09 UTC by RamLavi

**What this PR does / why we need it**:
Currently, the bumper script will fail upon the first bump failure.
We want to be able to run the bumper on all components even if one
component bump is broken.
The new behavior is that all found bumps will occur, and in the end if at least one
component failed to bump - the job will exit with error.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2020-12-20 17:00 UTC, RamLavi commented
/cherry-pick release-0.42

2020-12-21 07:52 UTC, RamLavi commented
/retest

2020-12-21 09:53 UTC, RamLavi commented
/retest

2020-12-21 11:49 UTC, RamLavi commented
/override pull-e2e-cluster-network-addons-operator-nmstate-functests
irrelevant to PR

2020-12-21 14:10 UTC, qinqon requested changes
nit

2020-12-21 14:10 UTC, qinqon commented on tools/bumper/bumper.go
> +		exitWithError(fmt.Errorf("Not all component bumps were successful: %s", strings.Join(failedComponents, ",")))
```suggestion
		exitWithError(fmt.Errorf("Not all component bumps were successful, failed components: %s", strings.Join(failedComponents, ",")))
```

2020-12-21 14:50 UTC, RamLavi commented on tools/bumper/bumper.go
> +		exitWithError(fmt.Errorf("Not all component bumps were successful: %s", strings.Join(failedComponents, ",")))
Done

2020-12-21 15:34 UTC, RamLavi commented
/retest

2020-12-22 08:28 UTC, qinqon commented
/lgtm
/approve

2020-12-22 09:26 UTC, merged