Release 0.48.0
kubevirt/cluster-network-addons-operator pull request #794
Opened 2021-03-03 07:09 UTC by qinqon

**What this PR does / why we need it**:
Release 0.48.0

**Special notes for your reviewer**:

**Release note**:

```release-note

```

2021-03-03 07:13 UTC, RamLavi commented
/lgtm
/approve

2021-03-03 10:54 UTC, qinqon commented
/override pull-e2e-cluster-network-addons-operator-nmstate-functests

known flaky

2021-03-09 07:29 UTC, RamLavi requested changes

2021-03-09 07:29 UTC, RamLavi commented on version/description
> +* bump ovs-cni to v0.19.1 (#786)
can you manually add #795 (and #796 if it's merged) ?

2021-03-09 08:29 UTC, RamLavi commented
/retest

2021-03-10 06:33 UTC, closed without merging